#!/usr/bin/perl

while (<>) {
    if (/#([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})/) {
        my ($r, $g, $b) = (hex($1), hex($2), hex($3));
        if ($b > $g && $b > $r) {
            print "$ARGV, $.: $_";
        }
    }
}
continue {
    if (eof) { $. = 0; }
}
