#!/bin/bash

scripts=${0%/*}

theme_type=$1; shift
[ $# -ge 1 ] && theme_dir=$1 || theme_dir=org
[ $# -ge 2 ] && names_dir=$2 || names_dir=./generated

case "$theme_type" in
    'dark')
        files=(
            $(find $theme_dir -name '*.css' -a -name '*dark*' -type f)
            $names_dir/gtk-color-names-dark.css
        );;
    'normal'|'')
        files=(
            $(find $theme_dir -name '*.css' -a '!' -name '*dark*' -type f)
            $names_dir/gtk-color-names.css
        );;
    *)
        echo "usage: $0 [dark|normal]" 2>&1
        ;;
esac

#echo "/* FILES: ${files[@]} */"
$scripts/rel_colors.pl -c "${files[@]}"
