#!/bin/bash

scripts=${0%/*}

[[ $# -ge 1 ]] && orig_theme_dir="$1" || dir="org"
[[ $# -ge 2 ]] && dest_dir="$2"       || dest_dir="."

do_normalize() {
    local def_file=$1; shift

    rm -f $def_file
    $scripts/normalize_colors $def_file "$@"
}

do_normalize $dest_dir/gtk-color-names.css \
    $(find $orig_theme_dir -name '*.css' -a '!' -name '*dark*' -type f)

do_normalize $dest_dir/gtk-color-names-dark.css \
    $(find $orig_theme_dir -name '*.css' -a -name '*dark*' -type f)
